<head>
	<link rel="icon" href="./ext_lib/images/denr.png" type="image/png">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>DTS Report</title>
</head>
	<style type="text/css">
		
		#header{
			width: 100%;
			height: 50px;
			margin:0px;
			position:fixed;
		}
		
		#header img{
			height: 70px;
		}
		
		#header ul{
			list-style-type: none;
			margin-left: 10px;
			padding: 0;
		}
		#header {
			font-size:14px;
		}

		#header h2{
			font-size:25px;
			margin: 0px;
		}	
				
		
		#main_content{
			width: 100%;
			font-size: 14px;
			margin-top:0px;
		}
		
		#main_content table{
			border-collapse:collapse;
			margin: 0px;
			border: 1px solid black;
			font-size:13px;
		}
		#main_content table td{
			border: 1px solid black;
			padding:2px;
		}
		#chk_box{
			border: 1px solid black;
			height: 10px;
			width: 10px;
			margin: 0px 5px 0px 0px;
		}
		#chk_box2{
			background-color:black;
			border: 1px solid black;
			height: 10px;
			width: 10px;
			margin: 0px 5px 0px 0px;
		}
		
		.report_table {
			border:1px solid black;
			border-collapse: collapse;
			width:100%;
			
		}
		.report_table td{
			border:1px solid black;
			padding:5px;
			text-align:center;
		}
		
		.page_break { page-break-after: always; }
	</style>

	<div id="header">
	
		<table style="margin:-30px 0px 0px 0px;">
				<tr>
				<td><img src="./ext_lib/images/denr.png" alt=""/></td>
				<td>
					<ul>
						<li><span style="font-size:12px;">Republic of the Philippines</span></li>
						<li><span style="font-size:15px;">Department of Environment and Natural Resources, Region 10</span></li>
						<li><span style="font-size:17px; font-weight:bold"><?php echo $this->session->userdata('off_log_penro');?></span></li>
						<li><span style="font-size:12px"><?php echo $this->session->userdata('off_log_address');?></span></li>
					</ul>
				</td>
				</tr>
		</table>
		
		<?php date_default_timezone_set('Asia/Manila');?>
		<table style="margin:-20px 0px 0px 350px;text-align:center">
				<tr>
				<td>
					<ul>
						<li><span style="font-size:17px; font-weight:bold">DOCUMENT TRACKING SYSTEM</span></li>
						<li><span style="font-size:15px;">Database Population Report (CY-<?php echo $rec_yr;?>)</span></li>
						<li><span style="font-size:12px;"><?php echo 'Generated by: '.$this->session->userdata('u_log_fname').' '.$this->session->userdata('u_log_lname');?></span></li>
						<li><span style="font-size:12px;"><?php echo 'Generated on: '.date('m/d/Y; h:i A');?></span></li>
					</ul>
				</td>
				</tr>
		</table>
	
	</div>
	
	
	<div id="main_content">
				<?php if($rep_id==1):?>
				
							<table class="report_table" style="margin-top:160px">
										
											<tr style="font-weight:bold">
												<td rowspan="2">Month</td>
												<td rowspan="2">No. of Documents Released</td>
												<td rowspan="2">No. of Documents Received</td>
												<td colspan="3">Level of Priority</td>
												<td colspan="<?php echo count($doc_type);?>">Document Type</td>
												<td colspan="5">Documents Preliminary Referral</td>
												<td colspan="5">Document Classification</td>
											</tr>
											<tr style="font-style:italic">
												<td>Low</td>
												<td>Normal</td>
												<td>High</td>
												<?php foreach($doc_type as $row):?>
													<td><?php echo $row['doc_description'];?></td>
												<?php endforeach;?>
												<td>MSD</td>
												<td>TSD</td>
												<td>EMB</td>
												<td>MGB</td>
												<td>PENR Officer Only</td>
												<td>Simple</td>
												<td>Complex</td>
												<td>Highly-Technical</td>
												<td>Legal Concern</td>
												<td>No Action Required</td>
											</tr>
											
											<?php 
												$subt = array();
											
												for($x=1;$x<=12;$x++):
												
												if($x<=6){$sem=1;}
												else{$sem=2;}
											?>
											<tr>
											<td style="text-align:left;width:180px"><?php echo date('F', mktime(0, 0, 0, $x, 10)); ;?></td>
											<td><?php $nod_rel = $controller->get_doc_released(date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec); echo number_format($nod_rel[0]['doc_count']); array_push($subt, array("sem"=>$sem,"nod_rel_".$sem=>$nod_rel[0]['doc_count']));?></td>
											<td>
											<?php 
											
												$nod_recv1 = $controller->get_doc_lop('Low',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
												$nod_recv2 = $controller->get_doc_lop('Normal',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
												$nod_recv3 = $controller->get_doc_lop('High',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec); 
												
												echo number_format($nod_recv1[0]['doc_count']+$nod_recv2[0]['doc_count']+$nod_recv3[0]['doc_count']);
												
												array_push($subt, array("sem"=>$sem,"nod_recv_".$sem=>($nod_recv1[0]['doc_count']+$nod_recv2[0]['doc_count']+$nod_recv3[0]['doc_count'])));
											
											?>
											</td>
											
											<td><?php $nod_low = $controller->get_doc_lop('Low',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec); echo number_format($nod_low[0]['doc_count']);  array_push($subt, array("sem"=>$sem,"nod_low_".$sem=>$nod_low[0]['doc_count']));?></td>
											<td><?php $nod_norm = $controller->get_doc_lop('Normal',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec); echo number_format($nod_norm[0]['doc_count']);  array_push($subt, array("sem"=>$sem,"nod_norm_".$sem=>$nod_norm[0]['doc_count']));?></td>
											<td><?php $nod_high = $controller->get_doc_lop('High',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec); echo number_format($nod_high[0]['doc_count']);  array_push($subt, array("sem"=>$sem,"nod_high_".$sem=>$nod_high[0]['doc_count']));?></td>
											
											<?php foreach($doc_type as $row):?>
											<td><?php $nod_type = $controller->get_doc_types($row['dt_id'],date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec); echo number_format($nod_type[0]['doc_count']);  array_push($subt, array("sem"=>$sem,"nod_type_".$sem."_".$row['dt_id']=>$nod_type[0]['doc_count']));?></td>
											<?php endforeach;?>
											
											<td><?php $nod_msd = $controller->get_offdiv(2,date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec); echo number_format($nod_msd[0]['doc_count']);  array_push($subt, array("sem"=>$sem,"nod_msd_".$sem=>$nod_msd[0]['doc_count']));?></td>
											<td><?php $nod_tsd = $controller->get_offdiv(3,date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec); echo number_format($nod_tsd[0]['doc_count']);  array_push($subt, array("sem"=>$sem,"nod_tsd_".$sem=>$nod_tsd[0]['doc_count']));?></td>
											<td><?php $nod_emb = $controller->get_offdiv(5,date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec); echo number_format($nod_emb[0]['doc_count']);  array_push($subt, array("sem"=>$sem,"nod_emb_".$sem=>$nod_emb[0]['doc_count']));?></td>
											<td><?php $nod_mgb = $controller->get_offdiv(4,date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec); echo number_format($nod_mgb[0]['doc_count']);  array_push($subt, array("sem"=>$sem,"nod_mgb_".$sem=>$nod_mgb[0]['doc_count']));?></td>
											<td><?php $nod_penro = $controller->get_penro_doc(date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec); echo number_format($nod_penro[0]['doc_count']);  array_push($subt, array("sem"=>$sem,"nod_penro_".$sem=>$nod_penro[0]['doc_count']));?></td>
											
											<td><?php $nod_simp = $controller->get_act_class('Simple',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec); echo number_format($nod_simp[0]['doc_count']);  array_push($subt, array("sem"=>$sem,"nod_simp_".$sem=>$nod_simp[0]['doc_count']));?></td>
											<td><?php $nod_comp = $controller->get_act_class('Complex',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec); echo number_format($nod_comp[0]['doc_count']);  array_push($subt, array("sem"=>$sem,"nod_comp_".$sem=>$nod_comp[0]['doc_count']));?></td>
											<td><?php $nod_hitech = $controller->get_act_class('Highly Technical',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec); echo number_format($nod_hitech[0]['doc_count']);  array_push($subt, array("sem"=>$sem,"nod_hitech_".$sem=>$nod_hitech[0]['doc_count']));?></td>
											<td><?php $nod_legcon = $controller->get_act_class('Legal Concern',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec); echo number_format($nod_legcon[0]['doc_count']);  array_push($subt, array("sem"=>$sem,"nod_legcon_".$sem=>$nod_legcon[0]['doc_count']));?></td>
											<td><?php $nod_noact = $controller->get_act_class_nar(date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec); echo number_format($nod_noact[0]['doc_count']);  array_push($subt, array("sem"=>$sem,"nod_noact_".$sem=>$nod_noact[0]['doc_count']));?></td>
											
										</tr>
										
										<?php if($x==6):?>
										<tr style="font-weight:bold;">
											<td style="text-align:left;width:180px">Sub-Total for 1st Semester</td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_rel_1')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_recv_1')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_low_1')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_norm_1')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_high_1')));?></td>
											
											<?php foreach($doc_type as $row):?>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_type_1_'.$row['dt_id'])));?></td>
											<?php endforeach;?>
											
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_msd_1')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_tsd_1')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_emb_1')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_mgb_1')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_penro_1')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_simp_1')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_comp_1')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_hitech_1')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_legcon_1')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_noact_1')));?></td>
										</tr>
										<?php endif;?>
										
										<?php if($x==12):?>
										<tr style="font-weight:bold;">
											<td style="text-align:left;width:180px">Sub-Total for 2nd Semester</td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_rel_2')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_recv_2')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_low_2')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_norm_2')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_high_2')));?></td>
											
											<?php foreach($doc_type as $row):?>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_type_2_'.$row['dt_id'])));?></td>
											<?php endforeach;?>
											
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_msd_2')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_tsd_2')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_emb_2')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_mgb_2')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_penro_2')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_simp_2')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_comp_2')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_hitech_2')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_legcon_2')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_noact_2')));?></td>
										</tr>
										<tr style="font-weight:bold;">
											<td style="text-align:left;width:180px">Grand Total for CY <?php echo $rec_yr;?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_rel_1'))+array_sum(array_column($subt, 'nod_rel_2')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_recv_1'))+array_sum(array_column($subt, 'nod_recv_2')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_low_1'))+array_sum(array_column($subt, 'nod_low_2')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_norm_1'))+array_sum(array_column($subt, 'nod_norm_2')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_high_1'))+array_sum(array_column($subt, 'nod_high_2')));?></td>
											
											<?php foreach($doc_type as $row):?>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_type_1_'.$row['dt_id']))+array_sum(array_column($subt, 'nod_type_2_'.$row['dt_id'])));?></td>
											<?php endforeach;?>
											
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_msd_1'))+array_sum(array_column($subt, 'nod_msd_2')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_emb_1'))+array_sum(array_column($subt, 'nod_tsd_2')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_emb_1'))+array_sum(array_column($subt, 'nod_emb_2')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_mgb_1'))+array_sum(array_column($subt, 'nod_mgb_2')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_penro_1'))+array_sum(array_column($subt, 'nod_penro_2')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_simp_1'))+array_sum(array_column($subt, 'nod_simp_2')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_comp_1'))+array_sum(array_column($subt, 'nod_comp_2')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_hitech_1'))+array_sum(array_column($subt, 'nod_hitech_2')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_legcon_1'))+array_sum(array_column($subt, 'nod_legcon_2')));?></td>
											<td><?php echo number_format(array_sum(array_column($subt, 'nod_noact_1'))+array_sum(array_column($subt, 'nod_noact_2')));?></td>
										</tr>
										<?php endif;?>


											
											<?php endfor;?>
											
									</table>
									

					
				
				
				
				
				<?php elseif($rep_id==2):?>
				
									<table class="report_table" style="margin-top:160px">
										
											<tr style="font-weight:bold;">
												<td rowspan="2">Month</td>
												<td colspan="2">Preliminary Routing by PENRO</td>
												<td colspan="2">Routing by MSD</td>
												<td colspan="2">Routing by TSD</td>
											</tr>
											<tr>
												<td>No. of Documents Received</td>
												<td>Average No. of Hours</td>
												<td>No. of Documents Routed</td>
												<td>Average No. of Hours</td>
												<td>No. of Documents Routed</td>
												<td>Average No. of Hours</td>
												
											</tr>
											<?php
												$subt = array();
												
												for($x=1;$x<=12;$x++):
												
													if($x<=6){$sem=1;}
													else{$sem=2;}
											?>
											<tr>
												<td style="text-align:left;width:120px"><?php echo date('F', mktime(0, 0, 0, $x, 10)); ;?></td>
												
												
												<td><?php echo $penro_tdocs = number_format(count($controller->get_doc_recv(date('M', mktime(0, 0, 0, $x, 10)),$rec_yr))); array_push($subt, array("sem"=>$sem,"penro_tdocs_".$sem=>$penro_tdocs));?></td>
												<td>
														<?php 
																$total_no_hrs = 0;
																$doc_no_recv = $controller->get_doc_recv(date('M', mktime(0, 0, 0, $x, 10)),$rec_yr);
																foreach($doc_no_recv as $row){
																	
																	$doc_dt_penro = $controller->get_logs_penro($row['doc_no']);
																
																	if(isset($doc_dt_penro[0]['e_dt']) AND isset($doc_dt_penro[1]['e_dt'])){
																		$dur_diff = date_diff(date_create($doc_dt_penro[0]['e_dt']),date_create($doc_dt_penro[1]['e_dt']));
													
																		$no_hrs = ((((int)$dur_diff->m*20)*8)+((int)$dur_diff->d*8))+(int)$dur_diff->h;
																		$total_no_hrs += $no_hrs;
																	}
																
																	
																}
																
																if(count($doc_no_recv)!=0){
																	echo $penro_tdocs_percent = number_format((int)$total_no_hrs/count($doc_no_recv),2);
																	array_push($subt, array("sem"=>$sem,"penro_tdocs_percent_".$sem=>$penro_tdocs_percent));
																}else{
																	echo "0";
																}
																
														
														?>
												</td>
												
												
												<td><?php echo $msd_tdocs = number_format(count($controller->get_doc_div_recv(2,date('M', mktime(0, 0, 0, $x, 10)),$rec_yr))); array_push($subt, array("sem"=>$sem,"msd_tdocs_".$sem=>$msd_tdocs));?></td>
												<td>
														<?php 
																$total_no_hrs = 0;
																$doc_no_div_recv = $controller->get_doc_div_recv(2,date('M', mktime(0, 0, 0, $x, 10)),$rec_yr);
																foreach($doc_no_div_recv as $row){
																	
																	$doc_dt_div = $controller->get_logs_div($row['doc_no']);
																
																	if(isset($doc_dt_div[0]['e_dt']) AND isset($doc_dt_div[1]['e_dt'])){
																		$dur_diff = date_diff(date_create($doc_dt_div[0]['e_dt']),date_create($doc_dt_div[1]['e_dt']));
													
																		$no_hrs = ((((int)$dur_diff->m*20)*8)+((int)$dur_diff->d*8))+(int)$dur_diff->h;
																		$total_no_hrs += $no_hrs;
																	}
																
																	
																}
																
																if(count($doc_no_div_recv)!=0){
																	echo $msd_tdocs_percent = number_format((int)$total_no_hrs/count($doc_no_div_recv),2);
																	array_push($subt, array("sem"=>$sem,"msd_tdocs_percent_".$sem=>$msd_tdocs_percent));
																}else{
																	echo "0";
																}
																
														
														?>
												</td>
												
												
												<td><?php echo $tsd_tdocs = number_format(count($controller->get_doc_div_recv(3,date('M', mktime(0, 0, 0, $x, 10)),$rec_yr))); array_push($subt, array("sem"=>$sem,"tsd_tdocs_".$sem=>$tsd_tdocs));?></td>
												<td>
														<?php 
																$total_no_hrs = 0;
																$doc_no_div_recv = $controller->get_doc_div_recv(3,date('M', mktime(0, 0, 0, $x, 10)),$rec_yr);
																foreach($doc_no_div_recv as $row){
																	
																	$doc_dt_div = $controller->get_logs_div($row['doc_no']);
																
																	if(isset($doc_dt_div[0]['e_dt']) AND isset($doc_dt_div[1]['e_dt'])){
																		$dur_diff = date_diff(date_create($doc_dt_div[0]['e_dt']),date_create($doc_dt_div[1]['e_dt']));
													
																		$no_hrs = ((((int)$dur_diff->m*20)*8)+((int)$dur_diff->d*8))+(int)$dur_diff->h;
																		$total_no_hrs += $no_hrs;
																	}
																
																	
																}
																
																if(count($doc_no_div_recv)!=0){
																	echo $tsd_tdocs_percent = number_format((int)$total_no_hrs/count($doc_no_div_recv),2);
																	array_push($subt, array("sem"=>$sem,"tsd_tdocs_percent_".$sem=>$tsd_tdocs_percent));
																}else{
																	echo "0";
																}
																
														
														?>
												</td>
												
											</tr>
											
											<?php if($x==6):?>
											<tr style="font-weight:bold;">
												<td style="text-align:left;">Sub-Total for 1st Semester</td>
												<td><?php echo number_format(array_sum(array_column($subt, 'penro_tdocs_1')));?></td>
												<td><?php echo number_format(array_sum(array_column($subt, 'penro_tdocs_percent_1'))/6,2);?></td>
												<td><?php echo number_format(array_sum(array_column($subt, 'msd_tdocs_1')));?></td>
												<td><?php echo number_format(array_sum(array_column($subt, 'msd_tdocs_percent_1'))/6,2);?></td>
												<td><?php echo number_format(array_sum(array_column($subt, 'tsd_tdocs_1')));?></td>
												<td><?php echo number_format(array_sum(array_column($subt, 'tsd_tdocs_percent_1'))/6,2);?></td>
											</tr>
											<?php endif;?>
											<?php if($x==12):?>
											<tr style="font-weight:bold;">
												<td style="text-align:left;">Sub-Total for 2nd Semester</td>
												<td><?php echo number_format(array_sum(array_column($subt, 'penro_tdocs_2')));?></td>
												<td><?php echo number_format(array_sum(array_column($subt, 'penro_tdocs_percent_2'))/6,2);?></td>
												<td><?php echo number_format(array_sum(array_column($subt, 'msd_tdocs_2')));?></td>
												<td><?php echo number_format(array_sum(array_column($subt, 'msd_tdocs_percent_2'))/6,2);?></td>
												<td><?php echo number_format(array_sum(array_column($subt, 'tsd_tdocs_2')));?></td>
												<td><?php echo number_format(array_sum(array_column($subt, 'tsd_tdocs_percent_2'))/6,2);?></td>
											</tr>
												<tr style="font-weight:bold;">
												<td style="text-align:left;">Grand Total for CY <?php echo $rec_yr;?></td>
												<td><?php echo number_format(array_sum(array_column($subt, 'penro_tdocs_1')));?></td>
												<td><?php echo  number_format(((array_sum(array_column($subt, 'penro_tdocs_percent_1'))/6)+(array_sum(array_column($subt, 'penro_tdocs_percent_2'))/6))/2,2);?></td>
												<td><?php echo number_format(array_sum(array_column($subt, 'msd_tdocs_1')));?></td>
												<td><?php echo  number_format(((array_sum(array_column($subt, 'msd_tdocs_percent_1'))/6)+(array_sum(array_column($subt, 'msd_tdocs_percent_2'))/6))/2,2);?></td>
												<td><?php echo number_format(array_sum(array_column($subt, 'tsd_tdocs_1')));?></td>
												<td><?php echo  number_format(((array_sum(array_column($subt, 'tsd_tdocs_percent_1'))/6)+(array_sum(array_column($subt, 'tsd_tdocs_percent_2'))/6))/2,2);?></td>
											</tr>
											<?php endif;?>
											
											
											<?php endfor;?>
											
											
											
									</table>
									
				
				
				
				
				
				
				<?php elseif($rep_id==3):?>
				
												<?php
													$subt = array();
													$subt_uni = array();
													
													$mstart=0;$mend=0;
													if($semestral==1){
														$mstart=1;
														$mend=6;
													}else{
														$mstart=7;
														$mend=12;
													}
													
													for($x=$mstart;$x<=$mend;$x++):
													
													if($x<=6){$sem=1;}
													else{$sem=2;}
												?>

												<?php $subt_m_simp=0;$subt_m_simp_c=0;$subt_m_ut=0;$subt_m_nar=0;$subt_m_df=0;$subt_m_pda=0;$subt_m_pda_c=0;$subt_m_pda_simp=0;$subt_m_pda_simp_c=0;$subt_m_pda_comp=0;$subt_m_pda_comp_c=0;$subt_m_pda_hitech=0;$subt_m_pda_hitech_c=0;$subt_m_pda_legcon=0;$subt_m_pda_legcon_c=0;?>
		
														<?php if($x==1 OR $x==7):?><br><br><br><br><br><br><br><br><br><?php endif;?>
														
														<h4 style="margin:10px 0px 10px 0px"><?php echo date('F', mktime(0, 0, 0, $x, 10)).' '.$rec_yr ;?></h4>
														<table class="report_table" style="font-size:16px;">
														<tr>
															<td><b>TYPE OF DOCUMENT</b></td>
															
															<?php foreach($off_sec as $row):?>
																<td><b><?php echo $row['sec_alias'];?></b></td>
															<?php endforeach;?>
																<td><b>TOTAL</b></td>
														</tr>
														
														
														<tr>
															<td style="text-align:left;width:250px">Total No. of Document Referral</td>
															
															<?php foreach($off_sec as $row):?>
																<td>
																	<?php 
																		$doc_sec_ref = $controller->get_doc_sec_ref($row['sec_id'],date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
																		
																		if(count($doc_sec_ref)!=0){
																			echo count($doc_sec_ref);
																			$subt_m_df+=count($doc_sec_ref);
																		}else{
																			echo "-";
																		}
																		array_push($subt, array("sem"=>$sem,"docref_no_".$row['sec_alias'].$sem=>count($doc_sec_ref)));
																	?>
																</td>
															<?php endforeach;?>
																
																<td>
																	<?php echo $subt_m_df;?>
																</td>
														</tr>
														
														<tr>
															<td style="text-align:left;width:180px">Simple (No.)</td>
															
															<?php $total_docs = 0;
															foreach($off_sec as $row):?>
																<td>
																	<?php 
																		$doc_total_hrs = 0;
																		
																		$doc_sec = $controller->get_doc_sec_uni($row['sec_id'],'Simple',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
																		
																		
																		if(count($doc_sec)!=0){
																			
																			echo count($doc_sec);
																			$total_docs+=count($doc_sec);
																			
																		}else{
																			echo "-";
																		}
																		array_push($subt_uni, array("sem"=>$sem,"simp_no_".$row['sec_alias'].$sem=>count($doc_sec)));
																	?>
																</td>
															<?php endforeach;?>
																
																<td>
																	<?php if($total_docs!=0){echo number_format($total_docs);}else{echo "0";}?>
																</td>
															
														</tr>
														
														<tr>
															<td style="text-align:left;width:180px">Simple Acted (No.)(Ave. Days)</td>
															
															<?php $total_docs = 0;$total_hrs = 0;
															foreach($off_sec as $row):?>
																<td>
																	<?php 
																		$doc_total_hrs = 0;
																		
																		$doc_sec = $controller->get_doc_sec($row['sec_id'],'Simple',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
																		
																		foreach($doc_sec as $dur){
																			
																			$exp_dur = explode(" ", $dur['nd_act']);
																			if(!empty($exp_dur[1])){	
																				if(strpos($exp_dur[1],'month')!==false){
																					$doc_no_hrs = ((int)$exp_dur[0]*20)*8;
																				}
																				elseif(strpos($exp_dur[1],'day')!==false){
																					$doc_no_hrs = (int)$exp_dur[0]*8;
																				}
																				elseif(strpos($exp_dur[1],'hr')!==false){
																					$doc_no_hrs = (int)$exp_dur[0];
																				}
																				else{
																					$doc_no_hrs = 0;
																				}
																				$doc_total_hrs+=$doc_no_hrs;
																				$total_hrs+=$doc_no_hrs;
																				
																			}
																		}
																		
																		if(count($doc_sec)!=0){
																			echo "(".count($doc_sec).") (".number_format(($doc_total_hrs/count($doc_sec))/8,2).")";
																			
																			$total_docs+=count($doc_sec);
																			//$subt_m_simp+= number_format($doc_total_hrs/count($doc_sec),2);
																			//$subt_m_simp_c++;
																		}else{
																			echo "-";
																		}
																		array_push($subt, array("sem"=>$sem,"simp_no_".$row['sec_alias'].$sem=>count($doc_sec),"simp_hrs_".$row['sec_alias'].$sem=>$doc_total_hrs));
																	?>
																</td>
															<?php endforeach;?>
																
																<td>
																	<?php if($total_docs!=0){echo "(".number_format($total_docs).") (".number_format(($total_hrs/$total_docs)/8,2).")";}else{echo "0";}?>
																</td>
															
														</tr>
														
														<tr>
															<td style="text-align:left;width:180px">Complex (No.)</td>
															
															<?php $total_docs = 0;
															foreach($off_sec as $row):?>
																<td>
																	<?php 
																		$doc_total_hrs = 0;
																		
																		$doc_sec = $controller->get_doc_sec_uni($row['sec_id'],'Complex',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
																		
																		
																		if(count($doc_sec)!=0){
																			
																			echo count($doc_sec);
																			$total_docs+=count($doc_sec);
																			
																		}else{
																			echo "-";
																		}
																		
																		array_push($subt_uni, array("sem"=>$sem,"comp_no_".$row['sec_alias'].$sem=>count($doc_sec)));
																		
																	?>
																</td>
															<?php endforeach;?>
																
																<td>
																	<?php if($total_docs!=0){echo number_format($total_docs);}else{echo "0";}?>
																</td>
															
														</tr>
																					
														<tr>
															<td style="text-align:left;width:180px">Complex Acted (No.)(Ave. Days)</td>
															
															<?php $total_docs = 0;$total_hrs = 0;
															foreach($off_sec as $row):?>
																<td>
																	<?php 
																		$doc_total_hrs = 0;
																		$doc_sec = $controller->get_doc_sec($row['sec_id'],'Complex',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
																		
																		foreach($doc_sec as $dur){
																			
																			$exp_dur = explode(" ", $dur['nd_act']);
																			if(!empty($exp_dur[1])){	
																				if(strpos($exp_dur[1],'month')!==false){
																					$doc_no_hrs = ((int)$exp_dur[0]*20)*8;
																				}
																				elseif(strpos($exp_dur[1],'day')!==false){
																					$doc_no_hrs = (int)$exp_dur[0]*8;
																				}
																				elseif(strpos($exp_dur[1],'hr')!==false){
																					$doc_no_hrs = (int)$exp_dur[0];
																				}
																				else{
																					$doc_no_hrs = 0;
																				}
																				$doc_total_hrs+=$doc_no_hrs;
																				$total_hrs+=$doc_no_hrs;
																			}
																		}
																		
																		if(count($doc_sec)!=0){
																			echo "(".count($doc_sec).") (".number_format(($doc_total_hrs/count($doc_sec))/8,2).")";
																			
																			$total_docs+=count($doc_sec);
																		}else{
																			echo "-";
																		}
																		array_push($subt, array("sem"=>$sem,"comp_no_".$row['sec_alias'].$sem=>count($doc_sec),"comp_hrs_".$row['sec_alias'].$sem=>$doc_total_hrs));
																	?>
																</td>
															<?php endforeach;?>
																
																<td>
																	<?php if($total_docs!=0){echo "(".number_format($total_docs).") (".number_format(($total_hrs/$total_docs)/8,2).")";}else{echo "0";}?>
																</td>
														</tr>
														
														<tr>
															<td style="text-align:left;width:180px">Highly Technical (No.)</td>
															
															<?php $total_docs = 0;
															foreach($off_sec as $row):?>
																<td>
																	<?php 
																		$doc_total_hrs = 0;
																		
																		$doc_sec = $controller->get_doc_sec_uni($row['sec_id'],'Highly Technical',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
																		
																		
																		if(count($doc_sec)!=0){
																			
																			echo count($doc_sec);
																			$total_docs+=count($doc_sec);
																			
																		}else{
																			echo "-";
																		}
																		
																		array_push($subt_uni, array("sem"=>$sem,"hitech_no_".$row['sec_alias'].$sem=>count($doc_sec)));
																		
																	?>
																</td>
															<?php endforeach;?>
																
																<td>
																	<?php if($total_docs!=0){echo number_format($total_docs);}else{echo "0";}?>
																</td>
															
														</tr>
														
														<tr>
															<td style="text-align:left;width:180px">Legal Concern (No.)</td>
															
															<?php $total_docs = 0;
															foreach($off_sec as $row):?>
																<td>
																	<?php 
																		$doc_total_hrs = 0;
																		
																		$doc_sec = $controller->get_doc_sec_uni($row['sec_id'],'Legal Concern',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
																		
																		
																		if(count($doc_sec)!=0){
																			
																			echo count($doc_sec);
																			$total_docs+=count($doc_sec);
																			
																		}else{
																			echo "-";
																		}
																		
																		array_push($subt_uni, array("sem"=>$sem,"legcon_no_".$row['sec_alias'].$sem=>count($doc_sec)));
																		
																	?>
																</td>
															<?php endforeach;?>
																
																<td>
																	<?php if($total_docs!=0){echo number_format($total_docs);}else{echo "0";}?>
																</td>
															
														</tr>
																					








															<?php $total_docs = 0;$total_hrs = 0;
															foreach($off_sec as $row):?>
															
																	<?php 
																		$doc_total_hrs = 0;
																		$doc_sec = $controller->get_doc_sec($row['sec_id'],'Highly Technical',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
																		
																		foreach($doc_sec as $dur){
																			
																			$exp_dur = explode(" ", $dur['nd_act']);
																			if(!empty($exp_dur[1])){	
																				if(strpos($exp_dur[1],'month')!==false){
																					$doc_no_hrs = ((int)$exp_dur[0]*20)*8;
																				}
																				elseif(strpos($exp_dur[1],'day')!==false){
																					$doc_no_hrs = (int)$exp_dur[0]*8;
																				}
																				elseif(strpos($exp_dur[1],'hr')!==false){
																					$doc_no_hrs = (int)$exp_dur[0];
																				}
																				else{
																					$doc_no_hrs = 0;
																				}
																				$doc_total_hrs+=$doc_no_hrs;
																				$total_hrs+=$doc_no_hrs;
																			}
																		}
																		
																		if(count($doc_sec)!=0){
																			//echo "(".count($doc_sec).") (".number_format(($doc_total_hrs/count($doc_sec))/8,2).")";
																			
																			$total_docs+=count($doc_sec);
																		}else{
																			//echo "-";
																		}
																		array_push($subt, array("sem"=>$sem,"hitech_no_".$row['sec_alias'].$sem=>count($doc_sec),"hitech_hrs_".$row['sec_alias'].$sem=>$doc_total_hrs));
																	?>
															
															<?php endforeach;?>
															
																
																	<?php //if($total_docs!=0){echo "(".number_format($total_docs).") (".number_format(($total_hrs/$total_docs)/8,2).")";}else{echo "0";}?>
														
															<?php $total_docs = 0;$total_hrs = 0;
															foreach($off_sec as $row):?>
															
																	<?php 
																		$doc_total_hrs = 0;
																		$doc_sec = $controller->get_doc_sec($row['sec_id'],'Legal Concern',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
																		
																		foreach($doc_sec as $dur){
																			
																			$exp_dur = explode(" ", $dur['nd_act']);
																			if(!empty($exp_dur[1])){	
																				if(strpos($exp_dur[1],'month')!==false){
																					$doc_no_hrs = ((int)$exp_dur[0]*20)*8;
																				}
																				elseif(strpos($exp_dur[1],'day')!==false){
																					$doc_no_hrs = (int)$exp_dur[0]*8;
																				}
																				elseif(strpos($exp_dur[1],'hr')!==false){
																					$doc_no_hrs = (int)$exp_dur[0];
																				}
																				else{
																					$doc_no_hrs = 0;
																				}
																				$doc_total_hrs+=$doc_no_hrs;
																				$total_hrs+=$doc_no_hrs;
																			}
																		}
																		
																		if(count($doc_sec)!=0){
																			//echo "(".count($doc_sec).") (".number_format(($doc_total_hrs/count($doc_sec))/8,2).")";
																			
																			$total_docs+=count($doc_sec);
																		}else{
																			//echo "-";
																		}
																		array_push($subt, array("sem"=>$sem,"legcon_no_".$row['sec_alias'].$sem=>count($doc_sec),"legcon_hrs_".$row['sec_alias'].$sem=>$doc_total_hrs));
																	?>
															
															<?php endforeach;?>
															
																
																	<?php //if($total_docs!=0){echo "(".number_format($total_docs).") (".number_format(($total_hrs/$total_docs)/8,2).")";}else{echo "0";}?>
														
														
														
														
														
														
															
														<tr>
															<td style="text-align:left;width:180px">Unclosed Transaction (No.)</td>
															
															<?php foreach($off_sec as $row):?>
																<td>
																	<?php 
																		$doc_sec_ut = $controller->get_doc_sec_ut($row['sec_id'],date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
																		
																		if(count($doc_sec_ut)!=0){
																			echo count($doc_sec_ut);
																			$subt_m_ut+=count($doc_sec_ut);
																		}else{
																			echo "-";
																		}
																		array_push($subt, array("sem"=>$sem,"ut_no_".$row['sec_alias'].$sem=>count($doc_sec_ut)));
																	?>
																</td>
															<?php endforeach;?>
															
																<td>
																	<?php echo $subt_m_ut;?>
																</td>
														
														</tr>
															
														<tr>
															<td style="text-align:left;width:180px">% Documents Acted</td>
															
															<?php foreach($off_sec as $row):?>
																<td>
																	<?php 
																		$doc_simple = $controller->get_doc_sec($row['sec_id'],'Simple',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
																		$doc_complex = $controller->get_doc_sec($row['sec_id'],'Complex',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
																		$doc_hitech= $controller->get_doc_sec($row['sec_id'],'Highly Technical',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
																		$doc_legcon= $controller->get_doc_sec($row['sec_id'],'Legal Concern',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
																		$doc_sec_nar = $controller->get_doc_sec_nar($row['sec_id'],date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
																		
																		$total_acted = count($doc_simple)+count($doc_complex)+count($doc_hitech)+count($doc_legcon)+count($doc_sec_nar);
																		
																		$doc_sec_ref = $controller->get_doc_sec_ref($row['sec_id'],date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
																		if(count($doc_sec_ref)!=0){
																			echo number_format(($total_acted/count($doc_sec_ref))*100,2)."%";
																			$subt_m_pda+= number_format(($total_acted/count($doc_sec_ref))*100,2);
																			$subt_m_pda_c++;
																		}else{
																			echo "-";
																		}
																		
																		
																	?>
																</td>
															<?php endforeach;?>
																
																<td>
																	<?php if($subt_m_pda_c!=0){echo number_format($subt_m_pda/$subt_m_pda_c,2)."%";}else{echo '0';}?>
																</td>
														</tr>
														
														<tr>
															<td style="text-align:left;width:180px">% Simple Documents Acted</td>
															
															<?php foreach($off_sec as $row):?>
																<td>
																	<?php 
																		$doc_simple = $controller->get_doc_sec($row['sec_id'],'Simple',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
																		$doc_sec = $controller->get_doc_sec_uni($row['sec_id'],'Simple',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
																		
																		if(count($doc_sec)!=0){
																			echo number_format((count($doc_simple)/count($doc_sec))*100,2)."%";
																			$subt_m_pda_simp+= number_format((count($doc_simple)/count($doc_sec))*100,2);
																			$subt_m_pda_simp_c++;
																		}else{
																			echo "-";
																		}
																		
																		
																	?>
																</td>
															<?php endforeach;?>
																
																<td>
																	<?php if($subt_m_pda_simp_c!=0){echo number_format($subt_m_pda_simp/$subt_m_pda_simp_c,2)."%";}else{echo '0';}?>
																</td>
														</tr>
														
														<tr>
															<td style="text-align:left;width:180px">% Complex Documents Acted</td>
															
															<?php foreach($off_sec as $row):?>
																<td>
																	<?php 
																		$doc_complex = $controller->get_doc_sec($row['sec_id'],'Complex',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
																		$doc_sec = $controller->get_doc_sec_uni($row['sec_id'],'Complex',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
																		
																		if(count($doc_sec)!=0){
																			echo number_format((count($doc_complex)/count($doc_sec))*100,2)."%";
																			$subt_m_pda_comp+= number_format((count($doc_complex)/count($doc_sec))*100,2);
																			$subt_m_pda_comp_c++;
																		}else{
																			echo "-";
																		}
																		
																		
																	?>
																</td>
															<?php endforeach;?>
																
																<td>
																	<?php if($subt_m_pda_comp_c!=0){echo number_format($subt_m_pda_comp/$subt_m_pda_comp_c,2)."%";}else{echo '0';}?>
																</td>
														</tr>
														
														<tr>
															<td style="text-align:left;width:180px">% Highly Technical Documents Acted</td>
															
															<?php foreach($off_sec as $row):?>
																<td>
																	<?php 
																		$doc_hitech = $controller->get_doc_sec($row['sec_id'],'Highly Technical',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
																		$doc_sec = $controller->get_doc_sec_uni($row['sec_id'],'Highly Technical',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
																		
																		if(count($doc_sec)!=0){
																			echo number_format((count($doc_hitech)/count($doc_sec))*100,2)."%";
																			$subt_m_pda_hitech+= number_format((count($doc_hitech)/count($doc_sec))*100,2);
																			$subt_m_pda_hitech_c++;
																		}else{
																			echo "-";
																		}
																		
																		
																	?>
																</td>
															<?php endforeach;?>
																
																<td>
																	<?php if($subt_m_pda_hitech_c!=0){echo number_format($subt_m_pda_hitech/$subt_m_pda_hitech_c,2)."%";}else{echo '0';}?>
																</td>
														</tr>
														
														<tr>
															<td style="text-align:left;width:180px">% Legal Concern Documents Acted</td>
															
															<?php foreach($off_sec as $row):?>
																<td>
																	<?php 
																		$doc_legcon = $controller->get_doc_sec($row['sec_id'],'Legal Concern',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
																		$doc_sec = $controller->get_doc_sec_uni($row['sec_id'],'Legal Concern',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
																		
																		if(count($doc_sec)!=0){
																			echo number_format((count($doc_legcon)/count($doc_sec))*100,2)."%";
																			$subt_m_pda_legcon+= number_format((count($doc_legcon)/count($doc_sec))*100,2);
																			$subt_m_pda_legcon_c++;
																		}else{
																			echo "-";
																		}
																		
																		
																	?>
																</td>
															<?php endforeach;?>
																
																<td>
																	<?php if($subt_m_pda_legcon_c!=0){echo number_format($subt_m_pda_legcon/$subt_m_pda_legcon_c,2)."%";}else{echo '0';}?>
																</td>
														</tr>
														
														<tr>
															<td style="text-align:left;width:180px">No Action Required (No.)</td>
															
															<?php foreach($off_sec as $row):?>
																<td>
																	<?php 
																		$doc_sec_nar = $controller->get_doc_sec_nar($row['sec_id'],date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
																		if(count($doc_sec_nar)!=0){
																			echo count($doc_sec_nar);
																			$subt_m_nar+=count($doc_sec_nar);
																		}else{
																			echo "-";
																		}
																		array_push($subt, array("sem"=>$sem,"nar_no_".$row['sec_alias'].$sem=>count($doc_sec_nar)));
																	?>
																</td>
															<?php endforeach;?>
															
																<td>
																	<?php echo $subt_m_nar;?>
																</td>
														</tr>
																				
															
														
													</table>
													
														<div class="page_break"></div>
														<br><br><br><br><br><br><br><br><br>
														
														<!--<?php if(($x%2)==0):?>
															<div class="page_break"></div>
															<br><br><br><br><br><br><br>
														<?php endif;?>-->
														
														<?php endfor;?>
													
														
														
														
												
														
													
													<?php 
														for($y=$semestral;$y<=$semestral;$y++):
														
														if($y==1){$sems="1ST SEMESTER";}
														else{$sems="2ND SEMESTER";}
													?>
													
													
													<?php $subt_m_simp=0;$subt_m_simp_c=0;$subt_m_ut=0;$subt_m_nar=0;$subt_m_df=0;$subt_m_pda=0;$subt_m_pda_c=0;$subt_m_pda_simp=0;$subt_m_pda_simp_c=0;$subt_m_pda_comp=0;$subt_m_pda_comp_c=0;$subt_m_pda_hitech=0;$subt_m_pda_hitech_c=0;$subt_m_pda_legcon=0;$subt_m_pda_legcon_c=0;?>
													
													<center><h3>SUMMARY REPORT (CY-<?php echo $rec_yr?>)</h3></center>
													
													<table class="report_table" style="font-size:16px;">
														<tr>
															<td><b>TYPE OF DOCUMENT</b></td>
															
															<?php foreach($off_sec as $row):?>
																<td><b><?php echo $row['sec_alias'];?></b></td>
															<?php endforeach;?>
																<td><b>TOTAL</b></td>
														</tr>
														
														<tr><td colspan="<?php echo count($off_sec)+2;?>" style="text-align:left"><h3 style="margin:0px"><?php echo $sems;?></h3></td></tr>
														
														<tr>
															<td style="text-align:left;width:250px">Total No. of Document Referral</td>
															
															<?php foreach($off_sec as $row):?>
																<td>
																	<?php 
																		echo number_format(array_sum(array_column($subt, "docref_no_".$row['sec_alias'].$y)));
																		$subt_m_df+=array_sum(array_column($subt, "docref_no_".$row['sec_alias'].$y));
																	?>
																</td>
															<?php endforeach;?>
																<td>
																	<?php echo number_format($subt_m_df);?>
																</td>
														</tr>
														
														<tr>
															<td style="text-align:left;width:180px">Simple (No.)</td>
															
															<?php $total_docs = 0;
															foreach($off_sec as $row):?>
																<td>
																	<?php 
																		$sec_doc_no = array_sum(array_column($subt_uni, "simp_no_".$row['sec_alias'].$y));
																		
																		if($sec_doc_no!=0){echo $sec_doc_no;}else{echo "-";}
																				
																		$total_docs+=$sec_doc_no;
																	?>
																</td>
															<?php endforeach;?>
																
																<td>
																	<?php if($total_docs!=0){echo number_format($total_docs);}else{echo "(0) (0)";}?>
																</td>
															
														</tr>
														
														<tr>
															<td style="text-align:left;width:180px">Simple Acted (No.)(Ave. Days)</td>
															
															<?php $total_docs = 0;$total_hrs = 0;
															foreach($off_sec as $row):?>
																<td>
																	<?php 
																		$sec_doc_no = array_sum(array_column($subt, "simp_no_".$row['sec_alias'].$y));
																		$sec_doc_hrs = array_sum(array_column($subt, "simp_hrs_".$row['sec_alias'].$y));
																		
																		if($sec_doc_no!=0){echo "(".$sec_doc_no.") (".number_format(($sec_doc_hrs/$sec_doc_no)/8,2).")";}else{echo "(0) (0)";}
																				
																		$total_docs+=$sec_doc_no;
																		$total_hrs+=$sec_doc_hrs;
																	?>
																</td>
															<?php endforeach;?>
																
																<td>
																	<?php if($total_docs!=0){echo "(".number_format($total_docs).") (".number_format(($total_hrs/$total_docs)/8,2).")";}else{echo "(0) (0)";}?>
																</td>
															
														</tr>
															
														<tr>
															<td style="text-align:left;width:180px">Complex (No.)</td>
															
															<?php $total_docs = 0;
															foreach($off_sec as $row):?>
																<td>
																	<?php 
																		$sec_doc_no = array_sum(array_column($subt_uni, "comp_no_".$row['sec_alias'].$y));
																		
																		if($sec_doc_no!=0){echo $sec_doc_no;}else{echo "-";}
																				
																		$total_docs+=$sec_doc_no;
																	?>
																</td>
															<?php endforeach;?>
																
																<td>
																	<?php if($total_docs!=0){echo number_format($total_docs);}else{echo "(0) (0)";}?>
																</td>
															
														</tr>
														
														<tr>
															<td style="text-align:left;width:180px">Complex Acted (No.)(Ave. Days)</td>
															
															<?php $total_docs = 0;$total_hrs = 0;
															foreach($off_sec as $row):?>
																<td>
																	<?php 
																		$sec_doc_no = array_sum(array_column($subt, "comp_no_".$row['sec_alias'].$y));
																		$sec_doc_hrs = array_sum(array_column($subt, "comp_hrs_".$row['sec_alias'].$y));
																		
																		if($sec_doc_no!=0){echo "(".$sec_doc_no.") (".number_format(($sec_doc_hrs/$sec_doc_no)/8,2).")";}else{echo "(0) (0)";}
																				
																		$total_docs+=$sec_doc_no;
																		$total_hrs+=$sec_doc_hrs;
																	?>
																</td>
															<?php endforeach;?>
																
																<td>
																	<?php if($total_docs!=0){echo "(".number_format($total_docs).") (".number_format(($total_hrs/$total_docs)/8,2).")";}else{echo "(0) (0)";}?>
																</td>
														</tr>
															
														<tr>
															<td style="text-align:left;width:180px">Highly Technical (No.)</td>
															
															<?php $total_docs = 0;
															foreach($off_sec as $row):?>
																<td>
																	<?php 
																		$sec_doc_no = array_sum(array_column($subt_uni, "hitech_no_".$row['sec_alias'].$y));
																		
																		if($sec_doc_no!=0){echo $sec_doc_no;}else{echo "-";}
																				
																		$total_docs+=$sec_doc_no;
																	?>
																</td>
															<?php endforeach;?>
																
																<td>
																	<?php if($total_docs!=0){echo number_format($total_docs);}else{echo "(0) (0)";}?>
																</td>
															
														</tr>
														
														<tr>
															<td style="text-align:left;width:180px">Legal Concern (No.)</td>
															
															<?php $total_docs = 0;
															foreach($off_sec as $row):?>
																<td>
																	<?php 
																		$sec_doc_no = array_sum(array_column($subt_uni, "legcon_no_".$row['sec_alias'].$y));
																		
																		if($sec_doc_no!=0){echo $sec_doc_no;}else{echo "-";}
																				
																		$total_docs+=$sec_doc_no;
																	?>
																</td>
															<?php endforeach;?>
																
																<td>
																	<?php if($total_docs!=0){echo number_format($total_docs);}else{echo "(0) (0)";}?>
																</td>
															
														</tr>
														
														<!--
														<tr>
															<td style="text-align:left;width:180px">Highly Technical (No.)(Ave. Days)</td>
															
															<?php $total_docs = 0;$total_hrs = 0;
															foreach($off_sec as $row):?>
																<td>
																	<?php 
																		$sec_doc_no = array_sum(array_column($subt, "hitech_no_".$row['sec_alias'].$y));
																		$sec_doc_hrs = array_sum(array_column($subt, "hitech_hrs_".$row['sec_alias'].$y));
																		
																		if($sec_doc_no!=0){echo "(".$sec_doc_no.") (".number_format(($sec_doc_hrs/$sec_doc_no)/8,2).")";}else{echo "(0) (0)";}
																				
																		$total_docs+=$sec_doc_no;
																		$total_hrs+=$sec_doc_hrs;
																	?>
																</td>
															<?php endforeach;?>
																
																<td>
																	<?php if($total_docs!=0){echo "(".number_format($total_docs).") (".number_format(($total_hrs/$total_docs)/8,2).")";}else{echo "(0) (0)";}?>
																</td>
														</tr>
														
														<tr>
															<td style="text-align:left;width:180px">Legal Concern (No.)(Ave. Days)</td>
															
															<?php $total_docs = 0;$total_hrs = 0;
															foreach($off_sec as $row):?>
																<td>
																	<?php 
																		$sec_doc_no = array_sum(array_column($subt, "legcon_no_".$row['sec_alias'].$y));
																		$sec_doc_hrs = array_sum(array_column($subt, "legcon_hrs_".$row['sec_alias'].$y));
																		
																		if($sec_doc_no!=0){echo "(".$sec_doc_no.") (".number_format(($sec_doc_hrs/$sec_doc_no)/8,2).")";}else{echo "(0) (0)";}
																				
																		$total_docs+=$sec_doc_no;
																		$total_hrs+=$sec_doc_hrs;
																	?>
																</td>
															<?php endforeach;?>
																
																<td>
																	<?php if($total_docs!=0){echo "(".number_format($total_docs).") (".number_format(($total_hrs/$total_docs)/8,2).")";}else{echo "(0) (0)";}?>
																</td>
														</tr>
														-->

														
														<tr>
															<td style="text-align:left;width:180px">Unclosed Transaction (No.)</td>
															
															<?php foreach($off_sec as $row):?>
																<td>
																	<?php 
																		echo number_format(array_sum(array_column($subt, "ut_no_".$row['sec_alias'].$y)));
																		$subt_m_ut+=array_sum(array_column($subt, "ut_no_".$row['sec_alias'].$y));
																	?>
																</td>
															<?php endforeach;?>
															
																<td>
																	<?php echo number_format($subt_m_ut);?>
																</td>
														
														</tr>
															
														<tr>
															<td style="text-align:left;width:180px">% Documents Acted</td>
															
															<?php foreach($off_sec as $row):?>
																<td>
																	<?php 
																		$doc_simple = array_sum(array_column($subt, "simp_no_".$row['sec_alias'].$y));
																		$doc_complex = array_sum(array_column($subt, "comp_no_".$row['sec_alias'].$y));
																		$doc_hitech = array_sum(array_column($subt, "hitech_no_".$row['sec_alias'].$y));
																		$doc_legcon = array_sum(array_column($subt, "legcon_no_".$row['sec_alias'].$y));
																		$doc_sec_nar = array_sum(array_column($subt, "nar_no_".$row['sec_alias'].$y));
																		
																		$total_acted = $doc_simple+$doc_complex+$doc_hitech+$doc_legcon+$doc_sec_nar;
																		
																		$doc_sec_ref = array_sum(array_column($subt, "docref_no_".$row['sec_alias'].$y));
																		if($doc_sec_ref!=0){
																			echo number_format(($total_acted/$doc_sec_ref)*100,2)."%";
																			$subt_m_pda+=($total_acted/$doc_sec_ref)*100;
																			$subt_m_pda_c++;
																			
																		}else{
																			echo "-";
																		}
																		
																	?>
																</td>
															<?php endforeach;?>
																
																<td>
																	<?php if($subt_m_pda_c!=0){echo number_format($subt_m_pda/$subt_m_pda_c,2)."%";}else{echo '0';}?>
																</td>
														</tr>
															
														<tr>
															<td style="text-align:left;width:180px">% Simple Documents Acted</td>
															
															<?php foreach($off_sec as $row):?>
																<td>
																	<?php 
																		$doc_simple = array_sum(array_column($subt, "simp_no_".$row['sec_alias'].$y));
																		$doc_sec = array_sum(array_column($subt_uni, "simp_no_".$row['sec_alias'].$y));
																		
																		if($doc_sec!=0){
																			echo number_format(($doc_simple/$doc_sec)*100,2)."%";
																			$subt_m_pda_simp+= number_format(($doc_simple/$doc_sec)*100,2);
																			$subt_m_pda_simp_c++;
																		}else{
																			echo "-";
																		}
																		
																		
																	?>
																</td>
															<?php endforeach;?>
																
																<td>
																	<?php if($subt_m_pda_simp_c!=0){echo number_format($subt_m_pda_simp/$subt_m_pda_simp_c,2)."%";}else{echo '0';}?>
																</td>
														</tr>
														
														<tr>
															<td style="text-align:left;width:180px">% Complex Documents Acted</td>
															
															<?php foreach($off_sec as $row):?>
																<td>
																	<?php 
																		$doc_complex = array_sum(array_column($subt, "comp_no_".$row['sec_alias'].$y));
																		$doc_sec = array_sum(array_column($subt_uni, "comp_no_".$row['sec_alias'].$y));
																		
																		if($doc_sec!=0){
																			echo number_format(($doc_complex/$doc_sec)*100,2)."%";
																			$subt_m_pda_comp+= number_format(($doc_complex/$doc_sec)*100,2);
																			$subt_m_pda_comp_c++;
																		}else{
																			echo "-";
																		}
																		
																		
																	?>
																</td>
															<?php endforeach;?>
																
																<td>
																	<?php if($subt_m_pda_comp_c!=0){echo number_format($subt_m_pda_comp/$subt_m_pda_comp_c,2)."%";}else{echo '0';}?>
																</td>
														</tr>
														
														<tr>
															<td style="text-align:left;width:180px">% Highly Technical Documents Acted</td>
															
															<?php foreach($off_sec as $row):?>
																<td>
																	<?php 
																		$doc_hitech= array_sum(array_column($subt, "hitech_no_".$row['sec_alias'].$y));
																		$doc_sec = array_sum(array_column($subt_uni, "hitech_no_".$row['sec_alias'].$y));
																		
																		if($doc_sec!=0){
																			echo number_format(($doc_hitech/$doc_sec)*100,2)."%";
																			$subt_m_pda_hitech+= number_format(($doc_hitech/$doc_sec)*100,2);
																			$subt_m_pda_hitech_c++;
																		}else{
																			echo "-";
																		}
																		
																		
																	?>
																</td>
															<?php endforeach;?>
																
																<td>
																	<?php if($subt_m_pda_hitech_c!=0){echo number_format($subt_m_pda_hitech/$subt_m_pda_hitech_c,2)."%";}else{echo '0';}?>
																</td>
														</tr>
														
														<tr>
															<td style="text-align:left;width:180px">% Legal Concern Documents Acted</td>
															
															<?php foreach($off_sec as $row):?>
																<td>
																	<?php 
																		$doc_legcon= array_sum(array_column($subt, "legcon_no_".$row['sec_alias'].$y));
																		$doc_sec = array_sum(array_column($subt_uni, "legcon_no_".$row['sec_alias'].$y));
																		
																		if($doc_sec!=0){
																			echo number_format(($doc_legcon/$doc_sec)*100,2)."%";
																			$subt_m_pda_legcon+= number_format(($doc_legcon/$doc_sec)*100,2);
																			$subt_m_pda_legcon_c++;
																		}else{
																			echo "-";
																		}
																		
																		
																	?>
																</td>
															<?php endforeach;?>
																
																<td>
																	<?php if($subt_m_pda_legcon_c!=0){echo number_format($subt_m_pda_legcon/$subt_m_pda_legcon_c,2)."%";}else{echo '0';}?>
																</td>
														</tr>
														
														<tr>
															<td style="text-align:left;width:180px">No Action Required (No.)</td>
															
															<?php foreach($off_sec as $row):?>
																<td>
																	<?php 
																		echo number_format(array_sum(array_column($subt, "nar_no_".$row['sec_alias'].$y)));
																		$subt_m_nar+=array_sum(array_column($subt, "nar_no_".$row['sec_alias'].$y));
																	?>
																</td>
															<?php endforeach;?>
															
																<td>
																	<?php echo number_format($subt_m_nar);?>
																</td>
														</tr>
													</table>		
													
													<?php if($y==1):?>
														<div class="page_break"></div>
														<br><br><br><br><br><br><br><br><br>
													<?php endif;?>
													
													<?php endfor;?>	
													
													
				<?php elseif($rep_id==4):?>
									
									<table class="report_table" style="margin-top:160px">
									<tr style="font-weight:bold">
										<td rowspan="2">Month</td>
										<td rowspan="2">No. of Documents Acted</td>
										<td colspan="2">Simple</td>
										<td colspan="2">Complex</td>
										<td colspan="2">Highly Technical</td>
										<td colspan="2">Legal Concern</td>
									</tr>
									<tr style="font-style:italic">
										<td>No. of Documents</td>
										<td>Average No. of Days</td>
										<td>No. of Documents</td>
										<td>Average No. of Days</td>
										<td>No. of Documents</td>
										<td>Average No. of Days</td>
										<td>No. of Documents</td>
										<td>Average No. of Days</td>
									</tr>
									
									<?php 
										$subt = array();
									
										for($x=1;$x<=12;$x++):
										
										if($x<=6){$sem=1;}
										else{$sem=2;}
									?>
									<tr>
										<td style="text-align:left;width:180px"><?php echo date('F', mktime(0, 0, 0, $x, 10)); ;?></td>
										<td>
										<?php  
										
											$nod_act1 = $controller->get_act_class('Simple',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
											$nod_act2 = $controller->get_act_class('Complex',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
											$nod_act3 = $controller->get_act_class('Highly Technical',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec); 
											
											echo number_format($nod_act1[0]['doc_count']+$nod_act2[0]['doc_count']+$nod_act3[0]['doc_count']);
											
											array_push($subt, array("sem"=>$sem,"nod_act_".$sem=>$nod_act1[0]['doc_count']+$nod_act2[0]['doc_count']+$nod_act3[0]['doc_count']));
										
										?>
										</td>
										
										<td><?php $nod_simp = $controller->get_act_class('Simple',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);  echo number_format($nod_simp[0]['doc_count']);  array_push($subt, array("sem"=>$sem,"nod_simp_".$sem=>$nod_simp[0]['doc_count']));?></td>
										<td>
											<?php 
												$doc_total_hrs = 0;
												$doc_noh = $controller->get_doc_noh('Simple',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
												
												foreach($doc_noh as $dur){
													
													$exp_dur = explode(" ", $dur['nd_act']);
													if(!empty($exp_dur[1])){
														if(strpos($exp_dur[1],'month')!==false){
															$doc_no_hrs = ((int)$exp_dur[0]*20)*8;
														}
														elseif(strpos($exp_dur[1],'day')!==false){
															$doc_no_hrs = (int)$exp_dur[0]*8;
														}
														elseif(strpos($exp_dur[1],'hr')!==false){
															$doc_no_hrs = (int)$exp_dur[0];
														}
														else{
															$doc_no_hrs = 0;
														}
														
														/* if($doc_no_hrs>23){
															$deduc = $doc_no_hrs-23.7;
															$doc_no_hrs = $doc_no_hrs-$deduc;
														} */
														
														$doc_total_hrs+=$doc_no_hrs;
													}
												}
												
												if(count($doc_noh)!=0){
													//$doc_total_hrs=$doc_total_hrs/8;
													echo number_format(($doc_total_hrs/count($doc_noh))/8,2);
													array_push($subt, array("sem"=>$sem,"ave_noh_simp_".$sem=>number_format($doc_total_hrs/count($doc_noh),2)));
													array_push($subt, array("sem"=>$sem,"no_rec_simp_".$sem=>1));
												}else{
													echo "0";
												}
												
											?>
										</td>
										<td><?php $nod_comp = $controller->get_act_class('Complex',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);  echo number_format($nod_comp[0]['doc_count']);  array_push($subt, array("sem"=>$sem,"nod_comp_".$sem=>$nod_comp[0]['doc_count']));?></td>
										<td>
											<?php 
												$doc_total_hrs = 0;
												$doc_noh = $controller->get_doc_noh('Complex',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
												
												foreach($doc_noh as $dur){
													
													$exp_dur = explode(" ", $dur['nd_act']);
													if(!empty($exp_dur[1])){	
														if(strpos($exp_dur[1],'month')!==false){
															$doc_no_hrs = ((int)$exp_dur[0]*20)*8;
														}
														elseif(strpos($exp_dur[1],'day')!==false){
															$doc_no_hrs = (int)$exp_dur[0]*8;
														}
														elseif(strpos($exp_dur[1],'hr')!==false){
															$doc_no_hrs = (int)$exp_dur[0];
														}
														else{
															$doc_no_hrs = 0;
														}
														
														/* if($doc_no_hrs>55){
															$deduc = $doc_no_hrs-50.5;
															$doc_no_hrs = $doc_no_hrs-$deduc;
														} */
														
														$doc_total_hrs+=$doc_no_hrs;
													}
												}
												
												if(count($doc_noh)!=0){
													//$doc_total_hrs=$doc_total_hrs/8;
													echo number_format(($doc_total_hrs/count($doc_noh))/8,2);
													array_push($subt, array("sem"=>$sem,"ave_noh_comp_".$sem=>number_format($doc_total_hrs/count($doc_noh),2)));
													array_push($subt, array("sem"=>$sem,"no_rec_comp_".$sem=>1));
												}else{
													echo "0";
												}
												
											?>
										</td>
										<td><?php $nod_hitech = $controller->get_act_class('Highly Technical',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);  echo number_format($nod_hitech[0]['doc_count']);  array_push($subt, array("sem"=>$sem,"nod_hitech_".$sem=>$nod_hitech[0]['doc_count']));?></td>
										<td>
											<?php 
												$doc_total_hrs = 0;
												$doc_noh = $controller->get_doc_noh('Highly Technical',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
												
												foreach($doc_noh as $dur){
													
													$exp_dur = explode(" ", $dur['nd_act']);
													if(!empty($exp_dur[1])){	
														if(strpos($exp_dur[1],'month')!==false){
															$doc_no_hrs = ((int)$exp_dur[0]*20)*8;
														}
														elseif(strpos($exp_dur[1],'day')!==false){
															$doc_no_hrs = (int)$exp_dur[0]*8;
														}
														elseif(strpos($exp_dur[1],'hr')!==false){
															$doc_no_hrs = (int)$exp_dur[0];
														}
														else{
															$doc_no_hrs = 0;
														}
														$doc_total_hrs+=$doc_no_hrs;
													}
												}
												
												if(count($doc_noh)!=0){
													//$doc_total_hrs=$doc_total_hrs/8;
													echo number_format(($doc_total_hrs/count($doc_noh))/8,2);
													array_push($subt, array("sem"=>$sem,"ave_noh_hitech_".$sem=>number_format($doc_total_hrs/count($doc_noh),2)));
													array_push($subt, array("sem"=>$sem,"no_rec_hitech_".$sem=>1));
												}else{
													echo "0";
												}
												
											?>
										</td>
										<td><?php $nod_legcon = $controller->get_act_class('Legal Concern',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);  echo number_format($nod_legcon[0]['doc_count']); array_push($subt, array("sem"=>$sem,"nod_legcon_".$sem=>$nod_legcon[0]['doc_count']));?></td>
										<td>
											<?php 
												$doc_total_hrs = 0;
												$doc_noh = $controller->get_doc_noh('Legal Concern',date('M', mktime(0, 0, 0, $x, 10)),$rec_yr,$start_rec,$end_rec);
												
												foreach($doc_noh as $dur){
													
													$exp_dur = explode(" ", $dur['nd_act']);
													if(!empty($exp_dur[1])){	
														if(strpos($exp_dur[1],'month')!==false){
															$doc_no_hrs = ((int)$exp_dur[0]*20)*8;
														}
														elseif(strpos($exp_dur[1],'day')!==false){
															$doc_no_hrs = (int)$exp_dur[0]*8;
														}
														elseif(strpos($exp_dur[1],'hr')!==false){
															$doc_no_hrs = (int)$exp_dur[0];
														}
														else{
															$doc_no_hrs = 0;
														}
														$doc_total_hrs+=$doc_no_hrs;
													}
												}
												
												if(count($doc_noh)!=0){
													//$doc_total_hrs=$doc_total_hrs/8;
													echo number_format(($doc_total_hrs/count($doc_noh))/8,2);
													array_push($subt, array("sem"=>$sem,"ave_noh_legcon_".$sem=>number_format($doc_total_hrs/count($doc_noh),2)));
													array_push($subt, array("sem"=>$sem,"no_rec_legcon_".$sem=>1));
												}else{
													echo "0";
												}
												
											?>
										</td>
									</tr>
									
									
									<?php 
									
										$no_rec_simp_1 = number_format(array_sum(array_column($subt, 'no_rec_simp_1')));
										$no_rec_comp_1 = number_format(array_sum(array_column($subt, 'no_rec_comp_1')));
										$no_rec_hitech_1 = number_format(array_sum(array_column($subt, 'no_rec_hitech_1')));
										$no_rec_legcon_1 = number_format(array_sum(array_column($subt, 'no_rec_legcon_1')));
										
										$no_rec_simp_2 = number_format(array_sum(array_column($subt, 'no_rec_simp_2')));
										$no_rec_comp_2 = number_format(array_sum(array_column($subt, 'no_rec_comp_2')));
										$no_rec_hitech_2 = number_format(array_sum(array_column($subt, 'no_rec_hitech_2')));
										$no_rec_legcon_2 = number_format(array_sum(array_column($subt, 'no_rec_legcon_2')));
										
									?>
									
									
									<?php if($x==6):?>
									<tr style="font-weight:bold;">
										<td style="text-align:left;width:180px">Sub-Total for 1st Semester</td>
										<td><?php echo number_format(array_sum(array_column($subt, 'nod_act_1')));?></td>
										<td><?php echo number_format(array_sum(array_column($subt, 'nod_simp_1')));?></td>
										<td><?php if($no_rec_simp_1!=0){echo number_format((array_sum(array_column($subt, 'ave_noh_simp_1'))/$no_rec_simp_1)/8,2);}else{echo '0';}?></td>
										<td><?php echo number_format(array_sum(array_column($subt, 'nod_comp_1')));?></td>
										<td><?php if($no_rec_comp_1!=0){echo number_format((array_sum(array_column($subt, 'ave_noh_comp_1'))/$no_rec_comp_1)/8,2);}else{echo '0';}?></td>
										<td><?php echo number_format(array_sum(array_column($subt, 'nod_hitech_1')));?></td>
										<td><?php if($no_rec_hitech_1!=0){echo number_format((array_sum(array_column($subt, 'ave_noh_hitech_1'))/$no_rec_hitech_1)/8,2);}else{echo '0';}?></td>
										<td><?php echo number_format(array_sum(array_column($subt, 'nod_legcon_1')));?></td>
										<td><?php if($no_rec_legcon_1!=0){echo number_format((array_sum(array_column($subt, 'ave_noh_legcon_1'))/$no_rec_legcon_1)/8,2);}else{echo '0';}?></td>
									</tr>
									<?php endif;?>
									
									<?php if($x==12):?>
									<tr style="font-weight:bold;">
										<td style="text-align:left;width:180px">Sub-Total for 2nd Semester</td>
										<td><?php echo number_format(array_sum(array_column($subt, 'nod_act_2')));?></td>
										<td><?php echo number_format(array_sum(array_column($subt, 'nod_simp_2')));?></td>
										<td><?php if($no_rec_simp_2!=0){echo number_format((array_sum(array_column($subt, 'ave_noh_simp_2'))/$no_rec_simp_2)/8,2);}else{echo '0';}?></td>
										<td><?php echo number_format(array_sum(array_column($subt, 'nod_comp_2')));?></td>
										<td><?php if($no_rec_comp_2!=0){echo number_format((array_sum(array_column($subt, 'ave_noh_comp_2'))/$no_rec_comp_2)/8,2);}else{echo '0';}?></td>
										<td><?php echo number_format(array_sum(array_column($subt, 'nod_hitech_2')));?></td>
										<td><?php if($no_rec_hitech_2!=0){echo number_format((array_sum(array_column($subt, 'ave_noh_hitech_2'))/$no_rec_hitech_2)/8,2);}else{echo '0';}?></td>
										<td><?php echo number_format(array_sum(array_column($subt, 'nod_legcon_2')));?></td>
										<td><?php if($no_rec_legcon_2!=0){echo number_format((array_sum(array_column($subt, 'ave_noh_legcon_2'))/$no_rec_legcon_2)/8,2);}else{echo '0';}?></td>
									</tr>
									<tr style="font-weight:bold;">
										<td style="text-align:left;width:180px">Grand Total for CY <?php echo $rec_yr;?></td>
										<td><?php echo number_format(array_sum(array_column($subt, 'nod_act_1'))+array_sum(array_column($subt, 'nod_act_2')));?></td>
										<td><?php echo number_format(array_sum(array_column($subt, 'nod_simp_1'))+array_sum(array_column($subt, 'nod_simp_2')));?></td>
										<td>
											<?php 
													if($no_rec_simp_1!=0){$ave_noh_simp_1 = array_sum(array_column($subt, 'ave_noh_simp_1'))/$no_rec_simp_1;}else{$ave_noh_simp_1 = 0;}
													if($no_rec_simp_2!=0){$ave_noh_simp_2 = array_sum(array_column($subt, 'ave_noh_simp_2'))/$no_rec_simp_2;}else{$ave_noh_simp_2 = 0;}
													
													if($no_rec_simp_2!=0){echo number_format((($ave_noh_simp_1+$ave_noh_simp_2)/2)/8,2);}
													else{echo number_format($ave_noh_simp_1/8,2);}
											?>
										</td>
										<td><?php echo number_format(array_sum(array_column($subt, 'nod_comp_1'))+array_sum(array_column($subt, 'nod_comp_2')));?></td>
										<td>
											<?php 
													if($no_rec_comp_1!=0){$ave_noh_comp_1 = array_sum(array_column($subt, 'ave_noh_comp_1'))/$no_rec_comp_1;}else{$ave_noh_comp_1 = 0;}
													if($no_rec_comp_2!=0){$ave_noh_comp_2 = array_sum(array_column($subt, 'ave_noh_comp_2'))/$no_rec_comp_2;}else{$ave_noh_comp_2 = 0;}
													
													if($no_rec_comp_2!=0){echo number_format((($ave_noh_comp_1+$ave_noh_comp_2)/2)/8,2);}
													else{echo number_format($ave_noh_comp_1/8,2);}
											?>
										</td>
										<td><?php echo number_format(array_sum(array_column($subt, 'nod_hitech_1'))+array_sum(array_column($subt, 'nod_hitech_2')));?></td>
										<td>
											<?php 
													if($no_rec_hitech_1!=0){$ave_noh_hitech_1 = array_sum(array_column($subt, 'ave_noh_hitech_1'))/$no_rec_hitech_1;}else{$ave_noh_hitech_1 = 0;}
													if($no_rec_hitech_2!=0){$ave_noh_hitech_2 = array_sum(array_column($subt, 'ave_noh_hitech_2'))/$no_rec_hitech_2;}else{$ave_noh_hitech_2 = 0;}
													
													if($ave_noh_hitech_2!=0){echo number_format((($ave_noh_hitech_1+$ave_noh_hitech_2)/2)/8,2);}
													else{echo number_format($ave_noh_hitech_1/8,2);}
													
											?>
										</td>
										<td><?php echo number_format(array_sum(array_column($subt, 'nod_legcon_1'))+array_sum(array_column($subt, 'nod_legcon_2')));?></td>
										<td>
											<?php 
													if($no_rec_legcon_1!=0){$ave_noh_legcon_1 = array_sum(array_column($subt, 'ave_noh_legcon_1'))/$no_rec_legcon_1;}else{$ave_noh_legcon_1 = 0;}
													if($no_rec_legcon_2!=0){$ave_noh_legcon_2 = array_sum(array_column($subt, 'ave_noh_legcon_2'))/$no_rec_legcon_2;}else{$ave_noh_legcon_2 = 0;}
													
													if($ave_noh_legcon_2!=0){echo number_format((($ave_noh_legcon_1+$ave_noh_legcon_2)/2)/8,2);}
													else{echo number_format($ave_noh_legcon_1/8,2);}
													
											?>
										</td>
									</tr>
									<?php endif;?>

									
									<?php endfor;?>
									
							</table>
											
				<?php elseif($rep_id==5):?>
										<br><br><br><br><br><br><br><br><br><br>
										
										<center><h3>CENTRALIZED UPLOADING OF INCOMING DOCUMENTS</h3></center>
										<table class="report_table">
					
											<tr style="font-weight:bold">
											
											<?php for($x=1;$x<=12;$x++): ?>
											
												<td><?php echo date('F', mktime(0, 0, 0, $x, 10));?><br><i style="font-weight:normal">(hrs:mins)</i></td>
												<?php if($x==6):?>
													<td>1st Semester Average</td>
												<?php endif;?>
												<?php if($x==12):?>
													<td>2nd Semester Average</td>
												<?php endif;?>
												
												
											<?php endfor;?>
											</tr>
											
											
											<tr>
											<?php 
											$subt = array();
											
											for($y=1;$y<=12;$y++):
											
												if($y<=6){$sem=1;}
												else{$sem=2;}
											?>
													<td>
														<?php 
														
															$total_mins=0;
															$ave_mins=0;
															$q1=0;$q2=0;
															
															$docs = $controller->get_docs(date('M', mktime(0, 0, 0, $y, 10)),$rec_yr); 
															
															foreach($docs as $row){
																
																
																$dt_stamp = $row['doc_date_rr']." ".$row['doc_time_rr'];
																$dt_upload = $row['rec_date']." ".$row['rec_time'];
																
																$dur_diff = date_diff(date_create($dt_stamp),date_create($dt_upload));
																$no_mins = (((((int)$dur_diff->m*20)*24)*60)+(((int)$dur_diff->d*24)*60))+((int)$dur_diff->h*60)+(int)$dur_diff->i;
																
																$total_mins+=$no_mins;
																
																
															}										
															
															
																if(count($docs)!=0){
																	$ave_mins=$total_mins/count($docs);	
																	echo sprintf('%02d', $ave_mins/60).":".sprintf('%02d', $ave_mins%60);
																	
																	array_push($subt, array("sem"=>$sem,"total_mins_".$sem=>$ave_mins,"cnt_".$sem=>1,));
																}
															
															
														?>
													</td>
													<?php if($y==6):?>
														<td><?php if(array_sum(array_column($subt, 'cnt_1'))!=0){$q1 = array_sum(array_column($subt, 'total_mins_1'))/array_sum(array_column($subt, 'cnt_1')); echo sprintf('%02d', $q1/60).":".sprintf('%02d', $q1%60);}?></td>
													<?php endif;?>
													<?php if($y==12):?>
														<td><?php if(array_sum(array_column($subt, 'cnt_2'))!=0){$q2 = array_sum(array_column($subt, 'total_mins_2'))/array_sum(array_column($subt, 'cnt_2')); echo sprintf('%02d', $q2/60).":".sprintf('%02d', $q2%60);}?></td>
													<?php endif;?>
											<?php endfor;?>
											</tr>
											</table>			
				<?php endif;?>			
				
				
	
	</div>
